### ISSUE TITLE
No Response

### ISSUE THREAD

**Issue by imerin** [ACDR/homebridge-yamaha-avr#13]
I'm getting constant no response from my yamaha receiver.

yamaha-nodjs is able to successfully communicate with the receiver, and the Active characteristic is indeed returned appropriately, however homekit insists that the plugin is giving me "no response".  My other home bridge accessories work correctly.

log snippet:

Yamaha-nodejs getBasicInfo Main_Zone {
  "YAMAHA_AV": {
    "$": {
      "rsp": "GET",
      "RC": "0"
    },
    "Main_Zone": [
      {
        "Basic_Status": [
          {
            "Power_Control": [
              {
                "Power": [
                  "Standby"
                ],
                "Sleep": [
                  "Off"
                ]
              }
            ],
            "Volume": [
              {
                "Lvl": [
                  {
                    "Val": [
                      "-440"
                    ],
                    "Exp": [
                      "1"
                    ],
                    "Unit": [
                      "dB"
                    ]
                  }
                ],
                "Mute": [
                  "Off"
                ],
                "Subwoofer_Trim": [
                  {
                    "Val": [
                      "0"
                    ],
                    "Exp": [
                      "1"
                    ],
                    "Unit": [
                      "dB"
                    ]
                  }
                ],
                "Scale": [
                  "dB"
                ]
              }
            ],
            "Input": [
              {
                "Input_Sel": [
                  "HDMI1"
                ],
                "Input_Sel_Item_Info": [
                  {
                    "Param": [
                      "HDMI1"
                    ],
                    "RW": [
                      "RW"
                    ],
                    "Title": [
                      "AppleTV"
                    ],
                    "Icon": [
                      {
                        "On": [
                          "1"
                        ],
                        "Off": [
                          "0"
                        ]
                      }
                    ],
                    "Src_Name": [
                      "Osdname:Living Room"
                    ],
                    "Src_Number": [
                      "1"
                    ]
                  }
                ]
              }
            ],
            "Surround": [
              {
                "Program_Sel": [
                  {
                    "Current": [
                      {
                        "Straight": [
                          "Off"
                        ],
                        "Enhancer": [
                          "Off"
                        ],
                        "Sound_Program": [
                          "Surround Decoder"
                        ]
                      }
                    ]
                  }
                ]
              }
            ],
            "Party_Info": [
              "Off"
            ],
            "Sound_Video": [
              {
                "Tone": [
                  {
                    "Bass": [
                      {
                        "Val": [
                          "0"
                        ],
                        "Exp": [
                          "1"
                        ],
                        "Unit": [
                          "dB"
                        ]
                      }
                    ],
                    "Treble": [
                      {
                        "Val": [
                          "0"
                        ],
                        "Exp": [
                          "1"
                        ],
                        "Unit": [
                          "dB"
                        ]
                      }
                    ]
                  }
                ],
                "Pure_Direct": [
                  {
                    "Mode": [
                      "Off"
                    ]
                  }
                ],
                "HDMI": [
                  {
                    "Standby_Through_Info": [
                      "On"
                    ],
                    "Output": [
                      {
                        "OUT_1": [
                          "On"
                        ],
                        "OUT_2": [
                          "On"
                        ]
                      }
                    ]
                  }
                ],
                "YPAO_Volume": [
                  "Auto"
                ],
                "Extra_Bass": [
                  "Off"
                ],
                "Adaptive_DRC": [
                  "Off"
                ],
                "Dialogue_Adjust": [
                  {
                    "Dialogue_Lift": [
                      "0"
                    ],
                    "Dialogue_Lvl": [
                      "2"
                    ],
                    "DTS_Dialogue_Control": [
                      "0"
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
} +47ms
  Accessory [Homebridge] Got Characteristic "Active" value: 0 +216ms

**Comment by imerin** [comment]
This appears to be due to a large amount of logging from another accessory.  Once that logging was silenced the yamaha receiver starting responding in homekit

**Comment by sommo** [comment]
How can I check those connections? Cause I’m having the same issue.. few hours ago.. I can’t get out.. Also tried to delete persist ad accessories folders restart homebridge service (dedicated to the only yamahaavr), removed ad readded via home app but didn’t resolve

**Comment by sommo** [comment]
I have two plugins for tvkit seems they start do conflict each other after weeks of working well.. into home app auto change their name into “other”.. really don’t know why cause homebridge side (log) all its ok

**Comment by imerin** [comment]
@sommo Hey so I was actually wrong, it wasn't from logging.  I had named my inputs differently than yamaha-avr was expecting.  If you dont have the current input in your configured inputs (e.g. HDMI1) then the code doesnt properly respond to the get ActiveIdentifier characteristic and homekit interprets that as no response

**Comment by ACDR** [comment]
@imerin - I've pushed a new version implementing some of the renamed input support from #14 and a fix for #9 . Can you please confirm whether this resolves this issue for you?

**Comment by imerin** [comment]
@ACDR Looks like you reverted the changes?

**Comment by ACDR** [comment]
Apologies, reverted the changes whilst I investigated https://github.com/ACDR/homebridge-yamaha-avr/issues/9#issuecomment-573293101.

If you could confirm whether `1.0.3` resolves this issue that would be much appreciated.

**Comment by slyoldfox** [comment]
@ACDR I have a RX-A2010 and added it to HomeBridge. The only thing that seems to be working is Power Off from within HomeBridge. Within HomeKit I see the No Response as well.

In the logs from homebridge I see:
[4/21/2020, 10:37:35 PM] [Yamaha RX-A2010] Power Off 
(which works).

Any pointers what I could try to debug this issue? I am using 1.0.3 of your plugin.

**Comment by ACDR** [comment]
This has been fixed in the beta release:
https://github.com/ACDR/homebridge-yamaha-avr/releases/tag/v2.0.0-beta.1

`npm install -g homebridge-yamaha-avr@beta`
