### ISSUE TITLE
Added accessories don’t appear in Homekit

### ISSUE THREAD

**Issue by bdag** [ACDR/homebridge-yamaha-avr#17]
Added and configured rx-a1080bl which works as accessory in Homebridge UI but never shows in Homekit.

**Comment by ACDR** [comment]
@bdag - did you have any luck with this, still an issue?

**Comment by geokvant** [comment]
Right after update to v.2.0.0 Yamaha RX-V575 disappeared from HomeKit UI. But available and works in HomeBridge accessoires tab. 
no errors in log
My config:
Homebridge Disk image on Raspberry
HB ver. 1.1.6
HB UI - latest

**Comment by ACDR** [comment]
The AVR is published as an external accessory in 2.0.0 so you'll need to add it manually.

Select "Add Accessory" in the Home app, then "I Don't Have a Code or Cannot Scan".

The AVR should then show as an option, enter your Homebridge PIN and you should be good to go.

<img src="https://user-images.githubusercontent.com/1072488/95639584-78824280-0af5-11eb-94cf-c6a8dd9793f4.png" width="320" />

**Comment by geokvant** [comment]
Yes! it works! Thank you!

**Comment by yogiee** [comment]
> 
> 
> The AVR is published as an external accessory in 2.0.0 so you'll need to add it manually.
> 
> Select "Add Accessory" in the Home app, then "I Don't Have a Code or Cannot Scan".
> 
> The AVR should then show as an option, enter your Homebridge PIN and you should be good to go.
> 
> <img alt="" width="320" src="https://user-images.githubusercontent.com/1072488/95639584-78824280-0af5-11eb-94cf-c6a8dd9793f4.png">

Sorry to bump this thread, but I'm facing the same issue... the accessory isn't appearing at all in the homekit and I've tried all possible fixes from completely cleaning the Homebridge config and re-installing plugin. The select an accessory dialog box either returns blank or keeping spinning without discovering the accessory. I'm using Homebridge 1.3.4 in Docker on RPi4, with plugin version 2.0.6 installed.

**Comment by ACDR** [comment]
> The select an accessory dialog box either returns blank or keeping spinning without discovering the accessory. I'm using Homebridge 1.3.4 in Docker on RPi4, with plugin version 2.0.6 installed.

Long shot, but have you tried completely closing the Home app and/or restarting your iOS device?

**Comment by yogiee** [comment]
> 
> 
> > The select an accessory dialog box either returns blank or keeping spinning without discovering the accessory. I'm using Homebridge 1.3.4 in Docker on RPi4, with plugin version 2.0.6 installed.
> 
> Long shot, but have you tried completely closing the Home app and/or restarting your iOS device?

Yes, I did... sadly, it didn't help.

**Comment by sambal0** [comment]
Unfortunately, I have a similar same issue as @bdag and @yogiee. Can not add the accessory through the Home app at all. It shows up and is responsive only through the Homebridge UI.
Tried to re-install the plugin twice already, turned off and rebooted homebridge and the HomePod as well as the iPhone several times. No changes. My configuration:
Raspberry 3B: Raspbian GNU/Linux Bullseye (11)
Plugin yamaha-avr: 3.0.0-beta.3
Homebridge: 1.5.0
Node: 16.17.0
Npm: 8.18.0
HomepodOS: 15.6
iOS: 15.6.1

**Comment by sambal0** [comment]
@ACDR you are genius! Unpairing the yamaha external accessory through the Homebridge Config UI solved the problem. The accessory showed up after a homebridge restart in the Home app and now everything works flawless. 
Thanks a lot for your help, did not know that the Homebridge Config UI has this option.
