### ISSUE TITLE
Failed to get available inputs from Yamaha R-N301

### ISSUE THREAD

**Issue by coldoatmeal** [ACDR/homebridge-yamaha-avr#18]
The plugin gets the basic configuration but then fails to get the available inputs. Not sure if the issue is in homebridge-yamaha-avr or in homebridge-yamaha.

`curl -X POST 'http://<IP address>/YamahaRemoteControl/ctrl' --data-binary '<?xml version="1.0" encoding="utf-8"?><YAMAHA_AV cmd="GET"><System><Config>GetParam</Config></System></YAMAHA_AV>'` returns `<YAMAHA_AV rsp="GET" RC="0"><System><Config><Model_Name>R-N301</Model_Name><System_ID>redacted</System_ID><Version>1.13/0.05</Version><Feature_Existence><Main_Zone>1</Main_Zone><Tuner>1</Tuner><Spotify>1</Spotify><Pandora>1</Pandora><SERVER>1</SERVER><NET_RADIO>1</NET_RADIO><AirPlay>1</AirPlay></Feature_Existence></Config></System></YAMAHA_AV>`

Looks like something fails parsing this response. I'm a system administrator for Windows and FreeBSD servers, so I'm outside of my expertise here.

**Comment by ACDR** [comment]
@coldoatmeal - this should be fixed in the beta release:
https://github.com/ACDR/homebridge-yamaha-avr/releases/tag/v2.0.0-beta.1

`npm install -g homebridge-yamaha-avr@beta`
