### ISSUE TITLE
Multiple YAMAHA AVR

### ISSUE THREAD

**Issue by clemi2408** [ACDR/homebridge-yamaha-avr#20]
Hi, 
i configured 2 Yamaha devices like this:

```
{
            "inputs": [
                {
                    "id": "HDMI1",
                    "name": "HDMI1"
                },
                {
                    "id": "HDMI2",
                    "name": "HDMI2"
                },
                {
                    "id": "HDMI3",
                    "name": "HDMI3"
                },
                {
                    "id": "HDMI4",
                    "name": "HDMI4"
                },
                {
                    "id": "HDMI5",
                    "name": "HDMI5"
                },
                {
                    "id": "HDMI6",
                    "name": "HDMI6"
                }
            ],
            "ip": "192.168.2.61",
            "name": "AVR Wohnzimmer",
            "platform": "yamaha-avr"
        },
        {
            "inputs": [
                {
                    "id": "HDMI1",
                    "name": "HDMI1"
                },
                {
                    "id": "HDMI2",
                    "name": "HDMI2"
                },
                {
                    "id": "HDMI3",
                    "name": "HDMI3"
                },
                {
                    "id": "HDMI4",
                    "name": "HDMI4"
                },
                {
                    "id": "HDMI5",
                    "name": "HDMI5"
                },
                {
                    "id": "HDMI6",
                    "name": "HDMI6"
                }
            ],
            "ip": "192.168.2.62",
            "name": "AVR Schlafzimmer",
            "platform": "yamaha-avr"
        }
```

Both devices are available in the Home APP, can be controlled (Power, Input).
But in the Control Center remote, only one Device is available.
Is this a BUG i am facing?

Regards
Clem

**Comment by ACDR** [comment]
Hi, looks like you're experiencing the same thing described here: https://github.com/ACDR/homebridge-yamaha-avr/issues/8

Looks like Control Centre still only supports a single device.

**Comment by clemi2408** [comment]
To be honest i dont think so, as both avr appear in the home app but only one in the remote section...

**Comment by ACDR** [comment]
Both will show in the Home app, yes. Though it seems only one TV remote per HomeBridge instance is supported in the Control Centre/Remote App. I'll have to dig into this more to see if this has changed.

**Comment by nitaybz** [comment]
You'll have to have it under its own bridge or either create the accessory as added accessory like cameras

**Comment by ACDR** [comment]
@clemi2408 - the AVR is now added as an external accessory in the beta release:
https://github.com/ACDR/homebridge-yamaha-avr/releases/tag/v2.0.0-beta.1

Note: the AVR accessory now needs to be added manually via "Add Accessory". Inputs are also managed entirely from within HomeKit and no longer require defining in the config to remove unwanted inputs.

npm install -g homebridge-yamaha-avr@beta
