### ISSUE TITLE
iOS 14 and new icons

### ISSUE THREAD

**Issue by CooperCGN** [ACDR/homebridge-yamaha-avr#26]
Hi,

since iOS 14 there seems to be icons now for AVRs. Right now a generic house icon is replacing the TV symbol.
https://imgur.com/gallery/ot2V52i

Any chance this could be included in this plugin too? This Denon plugin already has the changes included:
https://github.com/Martvvliet/homebridge-denon-heos/commit/d34ee5786ab900c4a838be4a2414c25887ecb195

**Comment by adrianopery** [comment]
Any target date to update the icon on the plugin?

**Comment by ACDR** [comment]
> Any target date to update the icon on the plugin?

Within the next day or so.

**Comment by ACDR** [comment]
The AVR is now added as an "Audio Receiver" with the new icon, along with a variety of other fixes and improvements here:
https://github.com/ACDR/homebridge-yamaha-avr/releases/tag/v2.0.0-beta.1

Note: The AVR in the beta version is now added as an external accessory, this needs to be added manually via "Add Accessory". Inputs are also managed entirely from within HomeKit and no longer require defining in the config to remove unwanted inputs.

`npm install -g homebridge-yamaha-avr@beta`

**Comment by adrianopery** [comment]
Hi hope you are well and safe.

I tried to install and received an error.

hoobs@hoobs:/home/hoobs/.hoobs/etc $ npm install -g
homebridge-yamaha-avr@beta

npm WARN deprecated request@2.88.2: request has been deprecated, see
https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN checkPermissions Missing write access to
/usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access
'/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access
'/usr/local/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access
'/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file
as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please
double-check the
npm ERR! permissions of the file and its containing directories, or try
running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-10-07T11_47_29_214Z-debug.log
hoobs@hoobs:/home/hoobs/.hoobs/etc $

Thanks,
Adriano

Em qua., 7 de out. de 2020 às 08:23, Aaron Rose <notifications@github.com>
escreveu:

**Comment by ACDR** [comment]
@adrianopery - seems to be an issue with the permissions of your global `node_modules` directory.

https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by adrianopery** [comment]
ok, thanks. I was reading the instructions you sent on the link but I'm
afraid to do.
I'll wait for the final version.

Em qua., 7 de out. de 2020 às 16:47, Aaron Rose <notifications@github.com>
escreveu:

**Comment by ACDR** [comment]
@adrianopery - it seems the error you're encountering is more related to your npm setup than the package itself.

You could try run the npm install command with `sudo`. That should get around the permissions error.

I do still recommend taking the steps outlined by npm to fix the error you're encountering & save you needing to use `sudo` when installing packages globally in future though.

**Comment by adrianopery** [comment]
I used with sudo ... 
But I can't see the new plugin on Hoobs.

hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo npm install -g homebridge-yamaha-avr@beta
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
+ homebridge-yamaha-avr@2.0.0-beta.2
updated 1 package in 6.758s
hoobs@hoobs:/home/hoobs/.hoobs/etc $

**Comment by adrianopery** [comment]
> @adrianopery - it seems the error you're encountering is more related to your npm setup than the package itself.
> 
> You could try run the npm install command with `sudo`. That should get around the permissions error.
> 
> I do still recommend taking the steps outlined by npm to fix the error you're encountering & save you needing to use `sudo` when installing packages globally in future though.

I did executed the steps and really fixed.
I could execute and install the homebridge but now, what is the next step?
I cant find my receiver on app home / New Accessory.

**Comment by ACDR** [comment]
> I cant find my receiver on app home / New Accessory.

@adrianopery - select "Add Accessory" in the Home app, then "I Don't Have a Code or Cannot Scan". 
The AVR should then show as an option, enter your Homebridge PIN and you should be good to go.

If it doesn't show up as an option you may need to clear your Homebridge cache.

![IMG_1466](https://user-images.githubusercontent.com/1072488/95639422-dd896880-0af4-11eb-9c25-9907e001b9c7.png)

**Comment by adrianopery** [comment]
I still have the old version on my homebridge.
Should I remove it?

Thanks

Em sex., 9 de out. de 2020 às 20:34, Aaron Rose <notifications@github.com>
escreveu:

**Comment by ACDR** [comment]
Yes, you'll need to remove the old version.

**Comment by adrianopery** [comment]
OK, I removed, clear the node cash and reinstall the beta version.
The point is that the beta version is not cataloged on Hoobs.
follow the execution result.

_pm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
+ homebridge-yamaha-avr@2.0.0-beta.2
updated 1 package in 22.688s
hoobs@hoobs:/home/hoobs/.hoobs/etc $_

**Comment by ACDR** [comment]
> OK, I removed, clear the node cash and reinstall the beta version.
> The point is that the beta version is not cataloged on Hoobs.
> follow the execution result.
> 
> hoobs@hoobs:/home/hoobs/.hoobs/etc $ npm install -g homebridge-yamaha-avr@beta
> npm WARN deprecated request@2.88.2: request has been deprecated, see [request/request#3142](https://github.com/request/request/issues/3142)
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> 
> * homebridge-yamaha-avr@2.0.0-beta.2
>   updated 1 package in 17.326s
>   hoobs@hoobs:/home/hoobs/.hoobs/etc $

I'm not familiar with Hoobs but from a quick search it appears it doesn't support globally installed packages...

Maybe this will help you:
https://github.com/hoobs-org/HOOBS/issues/186#issuecomment-538745028

**Comment by adrianopery** [comment]
> > OK, I removed, clear the node cash and reinstall the beta version.
> > The point is that the beta version is not cataloged on Hoobs.
> > follow the execution result.
> > hoobs@hoobs:/home/hoobs/.hoobs/etc $ npm install -g homebridge-yamaha-avr@beta
> > npm WARN deprecated request@2.88.2: request has been deprecated, see [request/request#3142](https://github.com/request/request/issues/3142)
> > npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> > 
> > * homebridge-yamaha-avr@2.0.0-beta.2
> >   updated 1 package in 17.326s
> >   hoobs@hoobs:/home/hoobs/.hoobs/etc $
> 
> I'm not familiar with Hoobs but from a quick search it appears it doesn't support globally installed packages...
> 
> Maybe this will help you:
> [hoobs-org/HOOBS#186 (comment)](https://github.com/hoobs-org/HOOBS/issues/186#issuecomment-538745028)

I really appreciate your support but I'll wait the final version.
when do you intent to publish the final version?

**Comment by ACDR** [comment]
@adrianopery - I'd give it one last go installing without the global flag. See if you have any luck.

`npm i homebridge-yamaha-avr@beta`

**Comment by adrianopery** [comment]
Hi Aaron thanks for your support.
I did your suggestion but didn't work.

hoobs@hoobs:/home/hoobs/.hoobs/etc $ npm i homebridge-yamaha-avr@beta
npm WARN deprecated request@2.88.2: request has been deprecated, see
https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN checkPermissions Missing write access to
/home/hoobs/.hoobs/node_modules/hap-nodejs
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/hoobs/.hoobs/node_modules/hap-nodejs
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access
'/home/hoobs/.hoobs/node_modules/hap-nodejs'
npm ERR!  [Error: EACCES: permission denied, access
'/home/hoobs/.hoobs/node_modules/hap-nodejs'] {
npm ERR!   stack: "Error: EACCES: permission denied, access
'/home/hoobs/.hoobs/node_modules/hap-nodejs'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/hoobs/.hoobs/node_modules/hap-nodejs'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file
as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please
double-check the
npm ERR! permissions of the file and its containing directories, or try
running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-10-13T10_20_50_271Z-debug.log


Em ter., 13 de out. de 2020 às 00:29, Aaron Rose <notifications@github.com>
escreveu:

**Comment by ACDR** [comment]
@adrianopery - The beta has been stable for me for the past week so I've gone ahead & released 2.0.0. 👍

**Comment by adrianopery** [comment]
I'm receiving the error on my Hoods.

13/10/2020 21:16:42 The requested platform "yamaha-avr" was not registered by any plugin.
13/10/2020 21:16:42 Your config.json is requesting the platform "yamaha-avr" which has not been published by any installed plugins.

**Comment by ACDR** [comment]
@adrianopery - unfortunately I don't think there's anything else I can really suggest to help with installation w' Hoobs.

I think you'll need to ask for help in the Hoobs repo: https://github.com/hoobs-org/HOOBS/issues

**Comment by adrianopery** [comment]
After I update I can't find on the Jason the plugin configurations.
Should I find the Yamaha platform?


Em ter., 13 de out. de 2020 às 21:37, Aaron Rose <notifications@github.com>
escreveu:

**Comment by ACDR** [comment]
Your previous error logs indicate it is configured in your config.json - but it can't find the plugin.

**Comment by adrianopery** [comment]
Aaron how are you.
I sent an issue to hoobs team and follow the answer...


Em ter., 13 de out. de 2020 às 22:32, Aaron Rose <notifications@github.com>
escreveu:
