### ISSUE TITLE
Partial functionality on a Yamaha TSR-7850?

### ISSUE THREAD

**Issue by psiberfunk** [ACDR/homebridge-yamaha-avr#28]
I added my Yamaha TSR-7850 with the simplest config I could think of.. and while I can change inputs and power cycle the unit, I can't change volume at all nor do I see remote functionality.

I'm running iOS 14.

Suggestions on what might be wrong 

Config:

  "platform": "yamaha-avr",
            "name": "Yamaha TSR-7850",
            "ip": "192.168.2.8"

**Comment by ACDR** [comment]
@psiberfunk - volume & remote functionality is only available via the Control Centre remote - is that not working for you?

**Comment by psiberfunk** [comment]
I think that’s the gap I didn’t understand,  probably best to close this now. From: Aaron RoseSent: Tuesday, October 6, 2020 10:58 PMTo: ACDR/homebridge-yamaha-avrCc: psiberfunk; MentionSubject: Re: [ACDR/homebridge-yamaha-avr] Partial functionality on a Yamaha TSR-7850? (#28) @psiberfunk - volume & remote functionality is only available via the Control Centre remote - is that not working for you?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
