### ISSUE TITLE
Manually specifying port in the beta

### ISSUE THREAD

**Issue by WTell** [ACDR/homebridge-yamaha-avr#30]
The beta seems to assign a random port number to the Yamaha AVR accessory on each launch of homebridge. This makes the plugin incompatible with any firewall software.

The plugin should either respect the `port` specified under `bridge` in `config.json`, or if this is not possible, the plugin should respect a `port` setting under `platforms` in `config.json`.

**Comment by ACDR** [comment]
@WTell - I've had a quick look into this and can't seem to find any information on defining the port to use for an external accessory.

I may be missing something, I'll have another look into it ASAP.

**Comment by ACDR** [comment]
@WTell - you can define the ports external accessories are assigned by setting a range in your Homebridge config.

https://github.com/homebridge/homebridge/blob/master/config-sample.json#L12

**Comment by WTell** [comment]
> @WTell - you can define the ports external accessories are assigned by setting a range in your Homebridge config.
> 
> https://github.com/homebridge/homebridge/blob/master/config-sample.json#L12

Thank you! This is what I was looking for. Worked very well. Should this be mentioned in the documentation for the beta?

**Comment by ACDR** [comment]
Added to README.
