### ISSUE TITLE
Multiple Zones

### ISSUE THREAD

**Issue by nitaybz** [ACDR/homebridge-yamaha-avr#31]
So I know there is a plugin out there that does it but your plugin is more maintained and well structured.

The dream plugin for Yamaha AVR for me will be to use your plugin on multiple zones and also have optional fan/bulb representing the Volume for automations.

Thanks and appreciate the work you've done so far🙏🏼

**Comment by ACDR** [comment]
Hi @nitaybz, you should be able to control the volume with automations using the native HomeKit Speaker device available for Yamaha AVRs. 

![image](https://user-images.githubusercontent.com/1072488/95383134-31564f00-0947-11eb-9bc9-e1bfd596b6f8.png)

I suppose this may not be available for all models though. 

I'll look into adding support for Zones & optionally adding a Speaker device for automation volume control. 👍

**Comment by nitaybz** [comment]
unfortunately I don't have a native HomeKit AVR.

> I'll look into adding support for Zones & optionally adding a Speaker device for automation volume control. 👍

That's super awesome! I would greatly appreciate it and I'm sure the entire Homebridge community will.
I'll be watching your plugin to see if we have any progress with that, for now I'm using other plugins with modifications I made but there are so many complications there that it will be better to write it from the start...
Then, I encountered your beta, looked at the code, and I thought to my self: "this guy can really do it!" ;)

Thanks🙏

**Comment by iSteve-O** [comment]
> Hi @nitaybz, you should be able to control the volume with automations using the native HomeKit Speaker device available for Yamaha AVRs.
> 
> <img alt="" width="320" src="https://user-images.githubusercontent.com/1072488/95383134-31564f00-0947-11eb-9bc9-e1bfd596b6f8.png">
> 
> I suppose this may not be available for all models though.
> 
> I'll look into adding support for Zones & optionally adding a Speaker device for automation volume control. 👍

I didn't know this either! I am so glad I decided to read through other issues LOL Thanks again for explaining in detail.

**Comment by ACDR** [comment]
> This only works for audio the receiver is actually playing (like airplay, net radio, tuner, etc) it doesn't work with HDMI inputs, for example. Oh well. Thanks still LOL

Could possibly solve this one with a Shortcut automation for now, using the "Get contents of URL" action with this URL:
`http://{AVR_IP}/YamahaExtendedControl/v1/main/setVolume?volume=50`

A shame there's still no way to directly control the volume of an AVR device in an automation. 😞

**Comment by ACDR** [comment]
Created a shortcut - this will ask for the AVR IP Address & desired volume on import. You can this trigger this shortcut in an automation to set the volume.

https://www.icloud.com/shortcuts/1e8b0433e975465780bfb44aa7f0a608

**Comment by iSteve-O** [comment]
> Created a shortcut - this will ask for the AVR IP Address & desired volume on import. You can then trigger this shortcut in an automation to set the volume.
> 
> 
> 
> https://www.icloud.com/shortcuts/1e8b0433e975465780bfb44aa7f0a608

Yeah that's awesome. Thank you for telling me that URL. I already made a shortcut using that LOL but I appreciate you showing me anyway!

**Comment by ACDR** [comment]
Additional zones can now be enabled in https://github.com/ACDR/homebridge-yamaha-avr/releases/tag/v3.0.0-beta.8 (see release notes for config - or enable with Homebridge config UI)

Volume "workaround" devices for each zone will be added in a later 3.0.0 beta release - these will also be opt-in via similar config setting as zones, disabled by default.
