### ISSUE TITLE
Not able to turn the unit off or on now

### ISSUE THREAD

**Issue by Mike92115** [ACDR/homebridge-yamaha-avr#33]
**Describe The Bug:**
Not able to turn the unit off or on now

**To Reproduce:**
Upgrade to the new 2.0 version

**Expected behavior:**
I updated to V2.0 from homebridge-yamaha-avr v1.0.4 and now there is no way to turn the unit off or on as it shows in HomeKit as a speaker 

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
        {
            "platform": "yamaha-avr",
            "ip": "10.0.1.38",
            "name": "Receiver"
        }
```

**Screenshots:**
https://mike-underwood.com/IMG_0517.jpeg

**Environment:**

* **Plugin Version**: v2.0.0 
* **Homebridge Version**: v1.2.3 
* **Node.js Version**: v12.18.3 
* **NPM Version**:  v6.14.7

* **Operating System**: Synology/Docker

**Comment by ACDR** [comment]
Some AVRs come with a native speaker accessory, this seems to be what you're seeing here.

The AVR is published as an external accessory in 2.0.0 so you'll need to add it manually.

Select "Add Accessory" in the Home app, then "I Don't Have a Code or Cannot Scan".

The AVR should then show as an option, enter your Homebridge PIN and you should be good to go.

<img src="https://user-images.githubusercontent.com/1072488/95639584-78824280-0af5-11eb-94cf-c6a8dd9793f4.png" width="320" />

**Comment by Mike92115** [comment]
Thank you for the fast reply, I had added the unit Manually, as before nothing was showing up for the unit so I saw that I needed to do that and did.

**Comment by ACDR** [comment]
I believe the native Speaker accessory is added in the same way - this plugin currently does not publish any speaker accessories. This plugin shows with an Audio Receiver icon (as pictured above).

Could you try removing the accessory from HomeKit then uninstalling the plugin entirely. Reinstall and see if you have any luck?

**Comment by Mike92115** [comment]
I removed the plugin from HomeBridge, restarted that and then added it back and it shows correctly when I go to add it to HomeKit but it's still showing there as a speaker with no way to turn it off or on.

**Comment by ACDR** [comment]
Did you see it as an Audio Receiver when you added it, with options to define inputs?

The speaker accessory you're seeing with media controls is a basic 1st party AirPlay 2 accessory published by Yamaha and is separate from Homebridge & this plugin's accessory. 

<img src="https://user-images.githubusercontent.com/1072488/96055775-721f0c80-0ee1-11eb-8996-a67091e4a597.png" width="120" />

**Comment by Mike92115** [comment]
No that is not what I am seeing, I am seeing this which shows it as a speaker.
![IMG_0518](https://user-images.githubusercontent.com/64978189/96057145-1d29ba80-0e3d-11eb-8715-3f4d123a3849.jpeg)

I renamed the device name and restarted HomeBridge. I am not seeing the new name, so something is cached.  I am going to try rebooting my Hub's and if that does not work letting it sit overnight to see if I see the updated name and hoping that when I do I see what you are seeing.

**Comment by Mike92115** [comment]
FYI I updated to 2.0.1 and now see this error on startup of HomeBridge, in case it makes a difference I am running HomeBridge in Docker on a Synology NAS.

[10/14/2020, 4:41:10 PM] [TSR-7850 Receiver] [Error: EACCES: permission denied, mkdir '/run/s6/services/.node_persist'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/run/s6/services/.node_persist'
}

**Comment by ACDR** [comment]
I've added error logging of cache issues - which will be why you're seeing that now.

You can set an alternative cache directory using the new `cacheDirectory` config option. This needs to be a directory your Homebridge instance can read/write to.

This may also have been why the AVR accessory wasn't showing for you previously.

**Comment by Mike92115** [comment]
THANK YOU! That was the issue, I had to update the path to /homebridge/node_persist otherwise the plugin was trying to write to homebridge Config UX  ./node_persist now I am seeing the Receiver correctly.

**Comment by sonoseco** [comment]
I just updated the plugin to 2.0.1 and now the receiver is no longer responding in the Home app. I'm also getting this:

```
[Error: EACCES: permission denied, mkdir '/var/lib/.node_persist'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/var/lib/.node_persist'
}
```

But strange is that it was working before with 2.0. I'm also using Config UX but on a regular Ubuntu install, so not sure what other path to use.

**Comment by Mike92115** [comment]
Looks similar to what I had, it is trying to create directory node_persist under path: '/var/lib/.node_persist'  Jump into the terminal and create your directory and then update the path to point to the location where you created that directory.  For me it was trying to create the path under the UI directory, so in terminal I created under the /homebridge directory then updated my path to be /homebridge/node_persist
