### ISSUE TITLE
Inputs

### ISSUE THREAD

**Issue by UKenGB** [ACDR/homebridge-yamaha-avr#36]
**Describe Your Problem:**
The Readme states 'Specific "favourite" inputs can be added manually …' How?

There is no guidance provided as to how this should be done. Admittedly I'm new to Homebridge, so maybe it would be obvious to someone with more experience, but I have no idea how 'inputs can be added manually' and so some assistance here would be appreciated.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by UKenGB** [comment]
I got it. These can be set in the UI once the AVR has been added to Home. However, there are still some questions about the 'Usage Notes':-

• _Quickly switch input using the information (i) button in the Control Centre remote_
There is no (i) button I can see.

• _Adjust the volume using the physical volume buttons on your iOS device whilst the Control Centre remote is open_
How does Homebridge do that? I can control the Apple TV from Control Centre without using HomeKit - with AVR on, just access the remote in CC and ATV can be controlled, but volume buttons do not work. I am not understanding how this plug-in can affect that.

Just trying to fully understand it all.

**Comment by ACDR** [comment]
<img src="https://user-images.githubusercontent.com/1072488/99369181-fc172680-2920-11eb-8fa5-6f07a5326c36.PNG" alt="" width="320" />

With the remote above open, and the AVR selected (as shown at the top) - you can hit the `i` button to the right of the `BACK` button to rotate through the inputs.

With the same remote open (must be via Control Centre) you can adjust the volume of the receiver using the physical volume buttons on the left of your iOS device.

**Comment by UKenGB** [comment]
Well that’s not what I see using iPadOS 14.2. The large central button is Menu here and with 2 buttons on either side, each corresponding to a Siri Remote button and none of them is an **i** which is not an actual Siri remote button.

I’ll check my iPhone, but I’m pretty sure it’s the same as the iPad. What device and iOS version are you using?

**Comment by ACDR** [comment]
Are you looking at the Control Centre remote or the Apple TV Remote app?

You can't control HomeKit devices using the remote app.

**Comment by UKenGB** [comment]
Ah, I've been missing the point here. Apologies, head too full of trying to set up doorbell notifications.

I realise now that the Yamaha AVR is selected at the top. I had the actual Apple TV selected as the Apple TV's Siri remote normally controls the Yamaha's volume and I didn't think to check what other devices were available to control. Sorry, stupid of me.

Now I understand. However, what is the function of the Cursor controls and the Pause/Play and Back buttons? What do they control on the Yamaha? I was thinking an on/off would be useful. Is that possible?

**Comment by ACDR** [comment]
No worries!

They mimic the same actions as the physical remote cursor controls, play pause, back etc... if you have HDMI-CEC enabled this will allow you to skip, rewind, pause, go back on whatever device you have set.

I can only tie actions to the buttons Apple make available to this remote. Of which all are utilised. The only arbitrary action being the `i` button, which is used to change to the next input.

If at some point Apple add more buttons, one being suited to power - I'll definitely add it. 👍
