### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by UKenGB** [ACDR/homebridge-yamaha-avr#37]
**Describe Your Problem:**

How can I configure it for multiple AVRs?

**Environment:**

* **Plugin Version**: 2.0.4
* **Homebridge Version**: 1.1.6
* **Node.js Version**: 14.15.0
* **NPM Version**: 6.14.8
* **Operating System**: MacOS 10.14.6

**Comment by try-and-error-and-repeat** [comment]
{
            "ip": "192.168.XXX.XXX",
            "name": "Yamaha RXV-1",
            "cacheDirectory": ".node_persist",
            "platform": "yamaha-avr"
        },
        {
            "ip": "192.168.XXX.XXY",
            "name": "Yamaha RXV-2",
            "cacheDirectory": ".node_persist",
            "platform": "yamaha-avr"
        }

Hope this helps

**Comment by UKenGB** [comment]
I thought read somewhere that trying to use multiple instances of the same platform caused problems, so I didn't try.

Thanks.

**Comment by try-and-error-and-repeat** [comment]
So did it work?
Than We can close this issue

**Comment by luc-ship-it** [comment]
I tried your suggestion, to change the config file. I did not work for me. I see only one device. Have you any other suggestions? Thanks!

**Comment by UKenGB** [comment]
Not tried it yet, been busy with other things. I'm using an Accessory to control the Yamahas at the moment, but will try this when I have some time.

**Comment by ash123-germany** [comment]
It worked perfect:
My settings:
   {
            "platform": "yamaha-avr",
            "plugin_map": {
                "plugin_name": "homebridge-yamaha-avr"
            },
            "ip": "192.168.178.37",
            "name": "Verstaerker",
            "cacheDirectory": ".node_persist"
        },
        {
            "platform": "yamaha-avr",
            "plugin_map": {
                "plugin_name": "homebridge-yamaha-avr"
            },
            "ip": "192.168.178.27",
            "name": "Radio",
            "cacheDirectory": ".node_persist"
        }

**Comment by marvelousmo** [comment]
Unfortunately, it gives me an error from the comma, marked bold:

{
"platform": "yamaha-avr",
"plugin_map": {
"plugin_name": "homebridge-yamaha-avr"
},
"ip": "192.168.178.37",
"name": "Verstaerker",
"cacheDirectory": ".node_persist"
}**,**
{
"platform": "yamaha-avr",
"plugin_map": {
"plugin_name": "homebridge-yamaha-avr"
},
"ip": "192.168.178.27",
"name": "Radio",
"cacheDirectory": ".node_persist"
}

**Comment by ACDR** [comment]
It's an array of platform objects.

```    
"platforms": [
        {
            "platform": "yamaha-avr",
            "plugin_map": {
                "plugin_name": "homebridge-yamaha-avr"
            },
            "ip": "192.168.178.37",
            "name": "Verstaerker",
            "cacheDirectory": ".node_persist"
        },
        {
            "platform": "yamaha-avr",
            "plugin_map": {
                "plugin_name": "homebridge-yamaha-avr"
            },
            "ip": "192.168.178.27",
            "name": "Radio",
            "cacheDirectory": ".node_persist"
        }
    ]
```

**Comment by marvelousmo** [comment]
THANK YOU! But now it gives me an error with the first colon:
<img width="915" alt="Bildschirmfoto 2022-08-26 um 10 58 36" src="https://user-images.githubusercontent.com/74103613/186867941-dd3b242b-8ef8-42ee-843c-d503602bcfd0.png">

**Comment by ACDR** [comment]
You'll want that platforms array in Homebridge config file, like in this sample:
https://github.com/homebridge/homebridge/blob/master/config-sample.json

**Comment by marvelousmo** [comment]
I am using HOOBS, probably that`s why

**Comment by marvelousmo** [comment]
Well Thank you anyways, very kind if you :-)
