### ISSUE TITLE
Can not import Speaker Accessory to my Home app

### ISSUE THREAD

**Issue by c-schulz-rd13** [ACDR/homebridge-yamaha-avr#38]
**I can not add the Speaker Accessory to my home app:**

My setup:

Yamaha RX-A870
Homebridge on a ubuntu server 20.04

Everything works well I can switch channels and switch the Receiver on and off.

**Screenshots:**
<img width="336" alt="Bildschirmfoto 2020-11-04 um 15 34 33" src="https://user-images.githubusercontent.com/6769715/98124288-475a1f80-1eb3-11eb-821a-bb17b5235b7e.png">

I can even see the speaker in my homebridge-ui. but when I try to control it nothing happens and I also can't find it when I try to manually add it to the home app as described below.

Is there an explanation for this behaviour or a chance to fix this?

**Any Help on this is very welcome**

**Logs:**

```
[11/4/2020, 3:17:17 PM] Homebridge v1.2.3 is running on port 51544.
[11/4/2020, 3:17:17 PM] AVR RX-A870 CFBA is running on port 36007.
[11/4/2020, 3:17:17 PM] Please add [AVR RX-A870 CFBA] manually in Home app. Setup Code:
```

**Plugin Config:**

```json
        {
            "ip": "192.168.xxx.xxx",
            "name": "AVR RX-A870",
            "cacheDirectory": "/homebridge/node-persist-rx-a870",
            "platform": "yamaha-avr"
        }
```

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: v1.2.3
* **Node.js Version**: v14.15.0
* **NPM Version**: v6.14.8
* **Operating System**: OSX 12.6 VirtualBox Ubuntu server 20.04 Docker (oznu/docker-homebridge)

**Comment by cwagdev** [comment]
I'm also not seeing speaker/volume control. Would love some help with this. The input control is working great!

**Comment by ACDR** [comment]
Volume is controlled using the physical volume buttons on your device with the AVR remote open via iOS Control Centre.

A separate speaker accessory hasn't yet been added to this plugin, the one visible in your screenshot may be an [AirPlay 2 accessory published natively by your AVR](https://usa.yamaha.com/news_events/2019/yamaha_enhances_home_audio_products.html).
