### ISSUE TITLE
Amp updating/unreponsive

### ISSUE THREAD

**Issue by kapps7** [ACDR/homebridge-yamaha-avr#39]
re yamaha rxa3080
**Describe The Bug:**
The Yamaha accessory shows in the home app but is unresponsive. It also doesnt show up in the accessories in Hoobs. This was working fine two versions prior of this plugin

**To Reproduce:**

**Expected behavior:**
Cannot control the yamaha avr

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```[11/8/2020, 1:18:30 AM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
08/11/2020, 7:18:30 pm Loaded plugin 'homebridge-yamaha-avr'
08/11/2020, 7:18:30 pm Loading 9 platforms...
08/11/2020, 7:18:30 pm [11/8/2020, 1:18:30 AM] Registering platform 'homebridge-yamaha-avr.yamaha-avr'
08/11/2020, 7:18:30 pm [webostv] Initializing webostv platform...

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```
{
            "platform": "yamaha-avr",
            "plugin_map": {
                "plugin_name": "homebridge-yamaha-avr"
            },
            "ip": "10.0.1.48",
            "name": "Yamaha AVR",
            "cacheDirectory": ".node_persist"
        }
**Screenshots:**

**Environment:**

* **Plugin Version**:2.0.4
* **Homebridge Version**: hoops 3.2.10 (issue existed on 3.2.9 and 3.52.6)
* **Node.js Version**: 12.16.3
* **NPM Version**: 
* **Operating System**: Hoobs

**Comment by proactivematter** [comment]
I also have this issue. My AVR shoes as updating / unresponsive in the Home app, but in the Homebridge CP under "Acessories" it shows as online and I can turn my receiver on/off through there.

**Comment by ACDR** [comment]
Hoobs may not have permission to read/write to the defined `cacheDirectory`, this may be of help:
https://github.com/ACDR/homebridge-yamaha-avr/issues/33#issuecomment-709529431

**Comment by try-and-error-and-repeat** [comment]
I think my issue is the same and I'am running homebridge - no hoobs

**Comment by proactivematter** [comment]
No hoobs here either.

**Comment by regnevah** [comment]
Same problem here with the RXA3080 - can control on home bridge but unresponsive in the home app.

I did stumble on one thing, if the amp input is set to Spotify, then it shows up in Home correctly and takes inputs.  Switching the input to something else seems to revert to the unresponsive state.

**Comment by proactivematter** [comment]
Yes, like Regnevah I've noticed the HomeKit acessory does respond when the AVR is set to select inputs. In my case, I noticed it shows up when set to AirPlay.
