### ISSUE TITLE
Problem with cache folder

### ISSUE THREAD

**Issue by jack-blackson** [ACDR/homebridge-yamaha-avr#41]
**Describe The Bug:**
Since 2-3 weeks, the connection to the AV Receiver is not working any more. Before that, it was working perfect. I saw today that there is an error in the log, which quite possibly shows what the problem is.

**To Reproduce:**
Restarted Homebridge already several times, have updated everything, but the problem still exists. 

**Expected behavior:**
The connection to the AV Receiver should work again - am not sure if the error is the reason, but expect that this is the case.

**Logs:**

```
[2020-11-14 16:35:24] [Yamaha RX-V473] 
          Could not create cache directory.
          Please check your Homebridge instance has permission to read/write to "/var/lib/.node_persist"
          or set a different cache directory using the "cacheDirectory" config property.
        
[2020-11-14 16:35:24] [Yamaha RX-V473] 
            Could not access cache.
            Please check your Homebridge instance has permission to access "undefined"
            or set a different cache directory using the "cacheDirectory" config property.
```

**Plugin Config:**

```json
{
            "platform": "yamaha-avr",
            "name": "Yamaha RX-V473",
            "ip": "192.168.1.103"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.0.4
* **Homebridge Version**: 1.1.6
* **Node.js Version**: 12.16.3
* **NPM Version**:  6.14.1
* **Operating System**:  Raspbian

**Comment by kbiswell** [comment]
How did you resolve this issue? I am still having this problem.

**Comment by ACDR** [comment]
Have you checked Homebridge can write to the defined (default) cacheDirectory?

**Comment by kbiswell** [comment]
How can I check that?

Sent from my iPhone

On Dec 5, 2020, at 1:58 AM, Aaron Rose <notifications@github.com> wrote:

﻿

Have you checked Homebridge can write to the defined (default) cacheDirectory?
