### ISSUE TITLE
Could not create cache directory.

### ISSUE THREAD

**Issue by bencharlesrhys** [ACDR/homebridge-yamaha-avr#42]
After updating to the latest yamaha-avr plugin version I've been receiving the following error:

[11/17/2020, 12:32:35 AM] [AV Receiver] 
          Could not create cache directory.
          Please check your Homebridge instance has permission to read/write to "/run/s6/services/homebridge-config-ui-x/.node_persist"
          or set a different cache directory using the "cacheDirectory" config property.
        
[11/17/2020, 12:32:35 AM] [AV Receiver] 
            Could not access cache.
            Please check your Homebridge instance has permission to access "undefined"
            or set a different cache directory using the "cacheDirectory" config property.

**Plugin Config:**
 {
            "ip": "XXX.XXX.X.X",
            "name": "AV Receiver",
            "cacheDirectory": ".node_persist",
            "platform": "yamaha-avr"
        }

**Environment:**

* **Plugin Version**: v2.0.4
* **Homebridge Version**: 1.1.6
* **Node.js Version**: 12.16.3
* **NPM Version**: 6.14.4
* **Operating System**: DSM Oznu Docker Image

**Comment by bencharlesrhys** [comment]
Resolved it by changing the cacheDirectory line to:

"cacheDirectory": "/homebridge/node-persist-avr",

**Comment by kbiswell** [comment]
I'm still stuck with this I tried what you did but it didn't work for me.
