### ISSUE TITLE
Yamaha RX-V771 no volume control

### ISSUE THREAD

**Issue by ArtGer1** [ACDR/homebridge-yamaha-avr#43]
**Describe Your Problem:**

Plugin works fine, I can put the V771 on, off and select a different Input. Only the volume control doesn't work. Maybe its because its a multi zone receiver. I only use the main zone. 
**Logs:**

12/1/2020, 11:59:09 AM [Yamaha AVR] Initializing yamaha-avr platform...
12/1/2020, 11:59:09 AM Loading 1 accessories...
12/1/2020, 11:59:09 AM [Pihole] Initializing Pihole accessory...
12/1/2020, 11:59:10 AM External port pool ran out of ports. Fallback to random assign.
12/1/2020, 11:59:10 AM Yamaha AVR is running on port 46827.
12/1/2020, 11:59:10 AM Please add [Yamaha AVR] manually in Home app. Setup Code: 
12/1/2020, 11:59:14 AM [Yamaha AVR] Current input: HDMI3 (HDMI3)

**Plugin Config:**

```json
{
            "platform": "yamaha-avr",
            "plugin_map": {
                "plugin_name": "homebridge-yamaha-avr"
            },
            "ip": "192.168.1.7",
            "name": "Yamaha AVR",
            "cacheDirectory": ".node_persist"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.0.4 
* **Homebridge Version**: Using HOOBS
* **Node.js Version**: 12.19.0
* **NPM Version**: 
* **Operating System**: HOOBS 3.3.1

**Comment by ACDR** [comment]
Volume is controlled via the physical device volume buttons whilst the AVR remote is open via Control Centre
