### ISSUE TITLE
Pure direct?

### ISSUE THREAD

**Issue by MojoDK** [ACDR/homebridge-yamaha-avr#47]
Any way to implement "Pure direct"?

**Comment by ACDR** [comment]
Apologies for the very late response to this, unfortunately though, there is still no elegant way of doing this within the current AVR HomeKit device implementation. 

You could however add a "switch" device to achieve this. I would prefer to keep this plug-in as a single AVR device, but you could try this plug-in with the below config: https://github.com/Supereg/homebridge-http-switch#readme

```
    "accessories": [
        {
          "accessory": "HTTP-SWITCH",
          "name": "Pure Direct Switch",
          
          "switchType": "stateful",
          
          "onUrl": "http://{AVR_IP}/YamahaExtendedControl/v1/main/setPureDirect?enable=true",
          "offUrl": "http://{AVR_IP}/YamahaExtendedControl/v1/main/setPureDirect?enable=false",
          
          "statusUrl": "http://{AVR_IP}/YamahaExtendedControl/v1/main/getStatus",
          "statusPattern": "\"pure_direct\":true"
        }   
    ]
```

**Comment by iSteve-O** [comment]
> Apologies for the very late response to this, unfortunately though, there is still no elegant way of doing this within the current AVR HomeKit device implementation.
> 
> You could however add a "switch" device to achieve this. I would prefer to keep this plug-in as a single AVR device, but you could try this plug-in with the below config: https://github.com/Supereg/homebridge-http-switch#readme
> 
> ```
>     "accessories": [
>         {
>           "accessory": "HTTP-SWITCH",
>           "name": "Pure Direct Switch",
>           
>           "switchType": "stateful",
>           
>           "onUrl": "http://{AVR_IP}/YamahaExtendedControl/v1/main/setPureDirect?enable=true",
>           "offUrl": "http://{AVR_IP}/YamahaExtendedControl/v1/main/setPureDirect?enable=false",
>           
>           "statusUrl": "http://{AVR_IP}/YamahaExtendedControl/v1/main/getStatus",
>           "statusPattern": "\"pure_direct\":true"
>         }   
>     ]
> ```

This is awesome. I love how you explain this. I suppose this way you could make a switch for any actions, including stateless ones if you have the URL scheme. Thank you for taking the time to write this out instead of just sayin "no" like a lot would.

**Comment by ACDR** [comment]
Pure Direct Switch added in https://github.com/ACDR/homebridge-yamaha-avr/releases/tag/v3.0.0-beta.9 (see release notes for example config to enable)
