### ISSUE TITLE
Tuner input (DAB) not able to be activated 

### ISSUE THREAD

**Issue by axelf2** [ACDR/homebridge-yamaha-avr#49]
After starting up the device via plugin, the input DAB (digital radio) is available, but cannot be selected
(after selection of the input channel DAB, the input switches to the former input and does not switch to DAB --> in effect the selection is ignored)

**To Reproduce:**
1) Start up device via plugin
2) Try to select DAB

**Expected behavior:**
Upon selection of DAB, the channell shall be activated

**Environment:**

homebridge-yamaha-avr v2.0.4 
* **Homebridge Version**: v1.1.7 
* **Node.js Version**: v14.15.3 
* **NPM Version**: v6.14.11 
* **Operating System**: Raspbian

Yamaha Device: RX-S601D

**Comment by FrankTheTankHH** [comment]
Hi!
Regrettably I cannot contrubute anything to the code - but maybe I have an idea about the reason for the curious reaction of the app:
The name of the receiver's input is "DAB+" (not "DAB") - but the app does not allow the "+" in the input name and simply deletes it. With the input name "DAB" the app cannot find the correct input which is in fact named "DAB+".
What do you think?

**Comment by ACDR** [comment]
Possibly resolved in `2.1.0-beta.9`. Please test and report back if you have a chance.
