### ISSUE TITLE
Plugin not responding after powering off (only when channel DAB selected)

### ISSUE THREAD

**Issue by axelf2** [ACDR/homebridge-yamaha-avr#50]
By the way: Great Plugin ! Thanks a lot !

After switching off the device manually on the device (RX-S601D) in mode DAB (digital radio), the plugin shows "device not available"

**To Reproduce:**
1) Switch to DAB on device (RX-S601D) 
2) Switch off the device manually (RX-S601D)
3) Kill Homekit-App on iPhone (to bridge delay of the app for updating the status of the plugin)

Comments: Other input channels than DAB work correctly

**Expected behavior:**
After switching off the device (any input channel selected), the plugin shall stay available.

**Environment:**

homebridge-yamaha-avr v2.0.4 
* **Homebridge Version**: v1.1.7 
* **Node.js Version**: v14.15.3 
* **NPM Version**: v6.14.11 
* **Operating System**: Raspbian

Yamaha Device: RX-S601D

**Comment by ACDR** [comment]
Please can you test with `2.1.0-beta.9` and report back if you have a chance. If still an issue will investigate further.
