### ISSUE TITLE
Not seeing volume icon

### ISSUE THREAD

**Issue by CurtisZM** [ACDR/homebridge-yamaha-avr#52]
**Describe Your Problem:**
I'm not seeing a volume icon on my IPAD. I have the icon for on/off and input selection. What am I missing here? Please assist. Thanks

- HB Version = 1.3.4
- OS = Windows

**Comment by ACDR** [comment]
Volume is controlled via the physical device volume buttons whilst the AVR remote is open via Control Centre

**Comment by Hadea4711** [comment]
Hi,

where do I find the Control Centre? Do you mean MusicCast?

**Comment by ACDR** [comment]
https://support.apple.com/en-us/HT210974

**Comment by Hadea4711** [comment]
HI ACDR,

tried that but without success. There is no way to change the volume with my physical buttons of my iPhone.

Or I'm the only one? ☝️

**Comment by ACDR** [comment]
Do you have the AVR remote selected in the Control Centre remote?

![image](https://user-images.githubusercontent.com/1072488/116469276-0bce6a00-a8c6-11eb-9e65-7215931fcaa6.png)

**Comment by Hadea4711** [comment]
Ok, found it, Thanks
