### ISSUE TITLE
No Volume Control

### ISSUE THREAD

**Issue by tStaiger** [ACDR/homebridge-yamaha-avr#6]
Hello together, 

I've installed the plugin and it works fine. But I don't see the option to set the volume up or down. I have the Yamaha RX-V475. Anything else is working (Input, On/Off).. 

Do you have an idea why this is not working? Thanks.

Tobias

**Comment by ACDR** [comment]
Hi Tobias, you can change the volume by using the physical volume buttons on your iOS device whilst you have the Control Center Remote open.

**Comment by tStaiger** [comment]
Oh sorry. It works ;) thanks
