### ISSUE TITLE
Volume control not working

### ISSUE THREAD

**Issue by superlarry** [ACDR/homebridge-yamaha-avr#61]
My Yamaha RX-V683 is working great with this plugin (thanks!), but I can only see power and input controls.  Is there something I can do to ensure the volume control shows up?

**Comment by ACDR** [comment]
Volume is controlled using the physical volume buttons on your iOS device whilst the Control Centre remote is open.

**Comment by superlarry** [comment]
My iOS volume control doesn't control the AVR volume while the Control Centre remote is open.  In the Home app on my Mac, the computer's volume controls aren't controlling the AVR either.

**Comment by ACDR** [comment]
As far as I know, Volume control with Mac isn't supported by HomeKit.

Just to be 100% certain, you do have the AVR selected in the Control Centre remote?

**Comment by superlarry** [comment]
Volume in iOS doesn't work for me in Home app or in the Control Centre.  I've tried several combinations of selecting the AVR.

In the Control Centre, the physical volume buttons don't seem to do anything, whether the Yamaha AVR is on or off.

![IMG_3702](https://user-images.githubusercontent.com/1747380/155608610-2134864c-674b-45cf-9a9d-df09b347811d.PNG)
![IMG_3700](https://user-images.githubusercontent.com/1747380/155608621-2586d211-2d8d-4c46-943f-8af8e11189dc.PNG)

**Comment by ACDR** [comment]
The Control Centre remote is opened via the bottom left corner button in your last screenshot.

**Comment by superlarry** [comment]
Thank you, I never would have found that.
