### ISSUE TITLE
Problem with "unexpected Input: V-Aux" since last update ... 

### ISSUE THREAD

**Issue by knikkabokka** [ACDR/homebridge-yamaha-avr#67]
Since the last update I get following error in the Homebridge-log: 

**Describe The Bug:**

In the home bridge-log there is an constant and repeating error: "Unexpected input: "V-Aux". 

- all the text in the error (see log more downwards), including the listing of the other available and apparently expected (? - the "Unexpected input is always V-Aux in the message ...) inputs, in written in red. 
- The error repeats and repeats and repeats ... twice every five minutes

**To Reproduce:**

- I Installed latest update of the Plugin
- I do start homebridge, look in the log, and the error appears and repeats as described
- After a restart of homebridge and even after a restart of the Raspberry Pi the error is still there

**Expected behavior:**

- No error in the log. 
- correct detection of the standard V-Aux input of my RXV-781

**Logs:**
```
[30.8.2022, 20:34:31] [Wohnzimmer] Unexpected input: "V-AUX" [
  { id: 'Tuner', name: 'Tuner' },
  { id: 'Napster', name: 'Napster' },
  { id: 'Spotify', name: 'Spotify' },
  { id: 'JUKE', name: 'JUKE' },
  { id: 'Qobuz', name: 'Qobuz' },
  { id: 'TIDAL', name: 'TIDAL' },
  { id: 'Deezer', name: 'Deezer' },
  { id: 'SERVER', name: 'SERVER' },
  { id: 'NETRADIO', name: 'NET RADIO' },
  { id: 'Bluetooth', name: 'Bluetooth' },
  { id: 'USB', name: 'USB' },
  { id: 'AirPlay', name: 'AirPlay' },
  { id: 'PHONO', name: 'PHONO' },
  { id: 'HDMI1', name: 'Blu-ray' },
  { id: 'HDMI2', name: 'Fire-TV Stick' },
  { id: 'HDMI3', name: 'Wii' },
  { id: 'HDMI4', name: 'HDMI4' },
  { id: 'HDMI5', name: 'HDMI5' },
  { id: 'AV1', name: 'AV1' },
  { id: 'AV2', name: 'AV2' },
  { id: 'AV3', name: 'AV3' },
  { id: 'AV4', name: 'AV4' },
  { id: 'AV5', name: 'AV5' },
  { id: 'AV6', name: 'AV6' },
  { id: 'VAUX', name: 'CD' },
  { id: 'AUDIO1', name: 'AUDIO1' },
  { id: 'AUDIO2', name: 'AUDIO2' }
]
```
... end repeats and repeats, endlessly ... 

**Plugin Config:**

{
            "ip": "xxx.xxx.xxx.xxx",
            "name": "Wohnzimmer",
            "cacheDirectory": "/var/lib/homebridge/.yamahaAVR",
            "platform": "yamaha-avr"
        },

**Screenshots:**

How do I insert a screenshot here?

**Environment:**

* **Plugin Version**: v2.1.0-beta.8
* **Homebridge Version**: v1.5.0
* **Node.js Version**: v16.17.0
* **NPM Version**: v8.15.0
* **Operating System**: Raspbian GNU/Linux 11 (bullseye)

**Comment by ACDR** [comment]
Extra logging has been added to handle inconsistencies with the active input identifier returned by the device on the repeating AVR state check (why the log repeats).

It appears in this case the active input identifier returned is "V-AUX" whereas the related identifier returned when creating the plug-in input is "VAUX". 

I'll add some extra handling for this scenario in a `2.1.0-beta.9` release today.

**Comment by ACDR** [comment]
`2.1.0-beta.9` published - please test and report back when you have a chance.
