### ISSUE TITLE
Warnings On Install

### ISSUE THREAD

**Issue by iSteve-O** [ACDR/homebridge-yamaha-avr#68]
**Describe The Bug:**
Warning of deprecated depends on install.

**To Reproduce:**
Install plugin using CLI.

**Expected behavior:**
No warnings.

**Logs:**

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

**Plugin Config:**

```json

        {
            "ip": "192.168.1.91",
            "name": "Yamaha AVR",
            "platform": "yamaha-avr",
            "_bridge": {
                "username": "0E:BA:68:77:A5:EE",
                "port": 35909
            }
```

**Screenshots:**
![Screen Shot 2022-08-30 at 10 31 07 PM](https://user-images.githubusercontent.com/10133108/187579669-292b0fd9-b912-4f54-9846-c4b3da90aa18.png)

**Environment:**

* **Plugin Version**: v2.1.0-beta.9
* **Homebridge Version**: v1.5.0
* **Node.js Version**: v16.17.0
* **NPM Version**: v8.18.0
* **Operating System**: Raspbian / hb-service

**Comment by ACDR** [comment]
Looks like these are originating from [yamaha-nodejs](https://github.com/PSeitz/yamaha-nodejs). 

Will see if we can get these packages updated over there, or failing that will fork and update.

**Comment by ACDR** [comment]
> or may just remove the `yamaha-nodejs` dependency and interact with the device directly.

In fact, I'll start experimenting with this tonight.

**Comment by iSteve-O** [comment]
> > or may just remove the `yamaha-nodejs` dependency and interact with the device directly.
> 
> In fact, I'll start experimenting with this tonight.

This sounds exciting! Good luck!

**Comment by ACDR** [comment]
Have published a beta release for v3, `3.0.0-beta.2` - if you could give this a whirl & report back how it goes that would be much appreciated!

`yamaha-nodejs` dependency has been removed and the plug-in now interfaces with the YamahaExtendedControl API directly.

https://github.com/ACDR/homebridge-yamaha-avr/releases/tag/v3.0.0-beta.2

**Comment by iSteve-O** [comment]
Hey so the warnings are all fixed. Install was super quick. It seems to have cached all of my inputs properly but when I rebooted the AVR using the music cast app I got some errors in the log. I have to turn on debug to get you more info but I'm working at the moment. Will try to get back to you with it ASAP.

`[Yamaha] Current input: hdmi1
[01/09/2022, 22:09:23] [Yamaha] Current input: hdmi1
[01/09/2022, 22:09:24] [Yamaha] Current input: hdmi1
[01/09/2022, 22:09:45] [Yamaha] Current input: hdmi1
[01/09/2022, 22:11:51] [homebridge-yamaha-avr] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.
[01/09/2022, 22:11:51] [homebridge-yamaha-avr] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.
[01/09/2022, 22:11:53] [homebridge-yamaha-avr] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.
[01/09/2022, 22:11:56] [homebridge-yamaha-avr] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.
[01/09/2022, 22:12:20] [Yamaha] Current input: hdmi1`

**Comment by ACDR** [comment]
Looks like the `/main/getStatus` endpoint was failing to get a response.  Still need to add handling for failing API responses when checking for the AVR status. Strange that it was failing to get a response though.

Do you get anything back from the AVR when you browse to the `http://{AVR_IP}/YamahaExtendedControl/v1/getStatus` endpoint whilst the log is returning 
```
{ power: undefined, input: undefined }
```

---

Just to clarify - was it working fine, then this happened when you turned the device off in the Music Cast App?

**Comment by iSteve-O** [comment]
> Looks like the `/main/getStatus` endpoint was failing to get a response. Added handling for failing API responses when checking for the AVR status in `3.0.0-beta.4`. Strange that it was failing to get a response though.
> 
> Do you get anything back from the AVR when you browse to the `http://{AVR_IP}/YamahaExtendedControl/v1/getStatus` endpoint whilst the log is returning
> 
> ```
> { power: undefined, input: undefined }
> ```
> 
> Just to clarify - was it working fine, then this happened when you turned the device off in the Music Cast App?

Yes, that's exactly what's happening. It. works fine before and after I reboot the receiver but during reboot homebridge just doesn't know what's going on and throws errors. 

I did what you said and tried to enter that URL for my receiver (http://192.168.1.91/YamahaExtendedControl/v1/getStatus) and before reboot I got "{"response_code":3}" and after reboot I got "{"response_code":1}" but during reboot the browser just held up like it was trying to reach something unreachable. it didn't return anything.

**Comment by ACDR** [comment]
Great - yeah looks like it's doing a hard shutdown/startup of the receiver - which is making the API inaccessible for a while. 

The error is now handled in the state check ping, when connection is lost it will post an "info" log as below a single time
```
        Cannot communicate with Yamaha AVR at 192.168.1.91.
        Connection will be restored automatically when the AVR begins responding.
```
It will then silently continue to ping the receiver until the connection is restored, then logging
```
Communication with Yamaha AVR at 192.168.1.91 restored
```

So, no more errors - just some info logs letting you know that connection was lost & restored. 😄

**Comment by iSteve-O** [comment]
> Great - yeah looks like it's doing a hard shutdown/startup of the receiver - which is making the API inaccessible for a while.
> 
> The error is now handled in the state check ping, when connection is lost it will post an "info" log as below a single time
> 
> ```
> Cannot communicate with Yamaha AVR at 192.168.1.91.
> Connection will be restored automatically when the AVR begins responding.
> ```
> 
> It will then silently continue to ping the receiver until the connection is restored, then logging
> 
> ```
> Communication with Yamaha AVR at 192.168.1.91 restored
> ```
> 
> So, no more errors - just some info logs letting you know that connection was lost & restored. 😄

That's awesome! Yeah, it seems to work very well. I'm glad you were able to dispatch with those install errors, even if benign they bother me LOL I really appreciate all of your work on the plugin lately. It works much better than the zone plugin I had been using, probably because of the constant polling this one does. The zone one takes much longer to update its status so is more difficult to use in scenes and automation. I'm trying to fix my LG tv integration now to see if the plugin can do a better job than native HomeKit. Even though this is doubtful, it should allow me to at least do more things with the TV in HomeKit. Next I have to figure out why every so often my TV screen will go black for a second sometimes once, sometimes over and over, and it seems to be related to the TV and AVR trying to set modes automatically or something. I may have to bypass this receiver's HDMI because of it which is really annoying. I don't know why I'm off on this, just mentioning it LOL

Great work!
