### ISSUE TITLE
Unexpected input "TUNER"

### ISSUE THREAD

**Issue by jack-blackson** [ACDR/homebridge-yamaha-avr#70]
Hey @ACDR !

Unfortunately, the error message from https://github.com/ACDR/homebridge-yamaha-avr/issues/51 is still appearing for me, even in version 2.1.0-beta.9.

![grafik](https://user-images.githubusercontent.com/13975634/187598606-60b73d74-d843-4e74-bc8b-c406cb84e635.png)

**Comment by ACDR** [comment]
@jack-blackson - please try `2.1.1`

**Comment by jack-blackson** [comment]
@ACDR  The error messages are gone - great :) Not I am only suffering of the issue that the AVR is appearing on my phone as "not responding" - but works fine in the homebridge UI. But I guess this is not an issue that is connected to your work. Thanks for looking at the issue

**Comment by ACDR** [comment]
@jack-blackson - I find quitting the Home app completely and opening again usually resolves this. 
The Home app seems to struggle a bit when Homebridge is rebooted whilst it's open.
