### ISSUE TITLE
Exclude secondary zones from creating TV & speaker accessory.

### ISSUE THREAD

**Issue by iSteve-O** [ACDR/homebridge-yamaha-avr#72]
**Is your feature request related to a problem? Please describe:**
I'd like to exclude the device for the 2nd zone from being ever being created for multi-zone AVR.

**Describe the solution you'd like:**
Some way to prevent the device being created for the 2nd zone of multi-zone receivers. 

**Describe alternatives you've considered:**
-

**Additional context:**
-
Thanks!

**Comment by ACDR** [comment]
`3.0.0-beta.8` adds config toggles for additional zone devices. They will be disabled by default.

<img width="820" alt="Screen Shot 2022-09-03 at 7 41 26 PM" src="https://user-images.githubusercontent.com/1072488/188261207-81a7af1f-c642-4123-9967-4bb781fd37b1.png">

**Comment by iSteve-O** [comment]
Perfect! I just had to remove the 2nd zone from the device cache in Homebridge settings, but maybe it would have disappeared if I had let it, I don't know. 

Related: Does not showing the 2nd TV unit for the 2nd zone actually save any resources? It seems like I read somewhere a long time ago that the more TV type devices you have the easier it is for things to get fouled up. I understand this is why they're all published as accessories that have to be added individually in HomeKit. Should I extrapolate from this that having one fewer TV devices will be somehow more stable?

Also, as a side note my Homebridge seems to be running much more smoothly after this last plug-in update but I think it's a coincidence because it ran badly when I had Yamaha-zone, when I had no Yamahas and when I had this one installed. The issue I've been having is where the GUI will freeze and it’ll take a while to reload itself or I'll have to reload the page with the browser. It also makes it hard to install things in the GUI because it will rarely make it through an install without freezing. I just figured it's one of my plugins causing it (Nest is suspect) or just too many plugins (I have 10 plugins, all with child bridges). Sometimes it gets better like this and then starts acting up again so we'll see. I just wondered if you had any thoughts in this since you're so helpful LOL Thanks again!

**Comment by ACDR** [comment]
> Perfect! I just had to remove the 2nd zone from the device cache in Homebridge settings, but maybe it would have disappeared if I had let it, I don't know. 

Wouldn't have removed itself when added manually. 😄

> Related: Does not showing the 2nd TV unit for the 2nd zone actually save any resources? It seems like I read somewhere a long time ago that the more TV type devices you have the easier it is for things to get fouled up. I understand this is why they're all published as accessories that have to be added individually in HomeKit. Should I extrapolate from this that having one fewer TV devices will be somehow more stable?

It would save some resources not initialising the additional devices, could be negligible though. As for stability, HomeKit can be finicky, seems especially so with TV devices, though usually only on startup of the Home app or if Homebridge is rebooted whilst the app is open etc.

> EDIT: it was a coincidence. It's acting up again as usual. I highly suspect Homebridge-nest, but will be eliminating another heavy one when my Eve Motion (w/Lux) arrives and I can get rid of my weather plug-in I use for a cloud cover sensor.

Odd, have you tried temporarily disabling those plugins to see if it helps at all?

**Comment by iSteve-O** [comment]
> > Perfect! I just had to remove the 2nd zone from the device cache in Homebridge settings, but maybe it would have disappeared if I had let it, I don't know. 
> 
> Wouldn't have removed itself when added manually. 😄
> 
> > Related: Does not showing the 2nd TV unit for the 2nd zone actually save any resources? It seems like I read somewhere a long time ago that the more TV type devices you have the easier it is for things to get fouled up. I understand this is why they're all published as accessories that have to be added individually in HomeKit. Should I extrapolate from this that having one fewer TV devices will be somehow more stable?
> 
> It would save some resources not initialising the additional devices, could be negligible though. As for stability, HomeKit can be finicky, seems especially so with TV devices, though usually only on startup of the Home app or if Homebridge is rebooted whilst the app is open etc.
> 
> > EDIT: it was a coincidence. It's acting up again as usual. I highly suspect Homebridge-nest, but will be eliminating another heavy one when my Eve Motion (w/Lux) arrives and I can get rid of my weather plug-in I use for a cloud cover sensor.
> 
> Odd, have you tried temporarily disabling those plugins to see if it helps at all?
> 
> 

I never added the 2nd zone, it just appeared after installing the one beta before you added the ability to disable, so I had to delete it from Homebridge. Never added it to HomeKit. I'm anal about what I add LOL to some degree. 

I have not tried disabling them because I thought I'd have to redo the scenes and automations in HomeKit after, or else I figured even though disabled maybe they still have some code running and disabling wouldn't be as good as removing for troubleshooting. 

The reason I say I think it's either nest or too many is because when I replaced my pi1 with a pi4 I paid attention as I added my plugins and it seemed to start happening after adding nest, but it was like the 5th plug-in. It also takes a while to notice if it's fixed. 

I do appreciate the info. I'll indeed try to keep the number of "tv" devices down. I already have 4 coming out of Homebridge, 5 total in 3 rooms.
