### ISSUE TITLE
Input names are wrong and can't be changed

### ISSUE THREAD

**Issue by Kienz** [ACDR/homebridge-yamaha-avr#74]
I named the Inputs (eg. HDMI1-> Playstation, HDMI3 -> Apple TV etc.) in the Yamaha AVR App. But the plugin displays HDMI1, HDMI2, HDMI3 etc.
And if I rename them in the Home App they are changed back after some seconds.

Version: 3.0.0

**Comment by ACDR** [comment]
Sounds like the plug-in may be unable to write to the cache directory.

Are you using the default cache directory or have you specified one?

Anything in the log?

**Comment by Kienz** [comment]
Homebridge is installed into /var/lib/homebridge
There exists the folder .yamahaAVR. In the plugin config /var/lib/homebridge/.yamahaAVR is set as cache directory.
If I change HDMI3 to Apple TV the content of  /var/lib/homebridge/.yamahaAVR/hdmi3 is:
```{"ConfiguredName":"Apple TV","CurrentVisibilityState":0}```
I can't see anything in the logs - there should be something like ```Set input (${input.id}) name to ${name}``` - or?

**Comment by Kienz** [comment]
Ok - now I see ```[Yamaha AVR] Set input (audio1) name to TV Audio```. And there a lot of ```[Yamaha AVR] AVR PING { power: 'standby', input: 'hdmi3' ```
Is it possible the AVR PING resets the naming? Because some names are changed - maybe timing problem?

**Comment by ACDR** [comment]
The PING simply checks for the power state and the active input ID & updates the app in HomeKit if it changes externally (e.g. with the physical AVR remote).

The cache for the main zone should be under a `main` directory, under `.YamahaAVR`. Have you tried removing the device (if it's one set up in v2 of the plug-in) and manually adding the new Main Zone device for v3?

**Comment by Kienz** [comment]
There is no ```main```directory under ```.yamahaAVR```. I complete deinstalled the plugin and removed the accessory. But still no ```main```folder.

**Comment by Kienz** [comment]
After the log output ```Current main input ...``` the names / visibility are changed back.

**Comment by ACDR** [comment]
Can you rename/delete the `.YamahaAVR` folder & reboot Homebridge - see if the directory is recreated?

**Comment by Kienz** [comment]
If I rename the inputs or change visibility and restart the homebridge it shows correct.

**Comment by Kienz** [comment]
The folder ```.yamahaAVR``` is recreated with all inputs - but no ```main``` folder.

**Comment by ACDR** [comment]
I think I've managed to replicate the issue. Appears we may be restoring the input name from a stale cache when HomeKit requests an updated name. Fix incoming.

As for the missing `main` cache directory - this isn't created if the `cacheDirectory` has been set in the config - a fix for this will also be be included (you'll should be able to simply move your existing cache data into this directory once updated).

**Comment by ACDR** [comment]
Should be fixed in `3.0.1-beta.0` - can you please test and confirm?

**Comment by alexanderjakob** [comment]
Downlaoded the beta version as well - could not change devices (like airplay, tv or so) anymore, just seeing "on, on, on, on, on, on, ..." in HomeKit

**Comment by ACDR** [comment]
You'll need to close the Home app and open again.

**Comment by alexanderjakob** [comment]
> You'll need to close the Home app and open again.

OMG - never mind, I'm so sorry -.-' works now!

**Comment by Kienz** [comment]
> Should be fixed in `3.0.1-beta.1` - can you please test and confirm?

It works. Thanks!

**Comment by ACDR** [comment]
https://github.com/ACDR/homebridge-yamaha-avr/releases/tag/v3.0.1
