### ISSUE TITLE
No TV Controls

### ISSUE THREAD

**Issue by BradJMelb** [ACDR/homebridge-yamaha-avr#8]
Hi,
The functionality in the Home app is working great (thanks), but when I go to Remotes in Control Centre it doesn’t show one for the Amplifier. I can see the two Apple TV’s that I have in the house as well as my LG TV (which is also via a home bridge plugin). Am I missing something here? It’s the final piece of the puzzle for me so I can change the Amplifier volume easily. 

Thanks,
Brad.

**Comment by ACDR** [comment]
Hi Brad, last I checked only one Homebridge TV Accessory appears in the Control Centre remote at a time, being dependent on which accessory initialises first when starting up Homebridge.

There may have been progress in resolving that issue since then. I’ll have another dig into this soon.

**Comment by BradJMelb** [comment]
Thanks Aaron, That would be great if you could take a look. I do have your plugin higher in my config file than the LG plugin. I can send through my config if you think that may help. 
Brad.

**Comment by ACDR** [comment]
If you would prefer your receiver in Control Centre in the meantime you may need to remove the LG plugin & restart Homebridge to ensure it pulls the AVR into the Control centre remote. 

Once a TV accessory has been added to the remote it will stay until the plugin is removed, you should then be able to add the LG plugin again.

**Comment by BradJMelb** [comment]
I've been reading more about this over at Homebridge and now understand what you mean. I'll keep watching for progress but in the mean time I've spun up a second Homebridge instance that has this plugin (with my original instance running the webs-tv plugin and I now have both remotes showing.

Thanks for pointing me in the right direction and I'll close this off.
