### ISSUE TITLE
Pure Direct Switch and Volume Device are always in Home

### ISSUE THREAD

**Issue by slydlake** [ACDR/homebridge-yamaha-avr#81]
Hi,
I active both settings to test it, but I don't need it anymore. I disabled the checks in the setting - and restarted home bridge of course. But both devices are still there.
Can you fix it, that the devices are only available when the checkboxes are filled?

`{
    "ip": "192.168.178.95",
    "name": "AV Receiver",
    "cacheDirectory": "~/.homebridge/.yamahaAVR",
    "enablePureDirectSwitch": false,
    "volumeAccessoryEnabled": false,
    "zone2Enabled": false,
    "zone3Enabled": false,
    "zone4Enabled": false,
    "platform": "yamaha-avr"
}`

**Comment by ACDR** [comment]
They may have been cached by HomeBridge. You can either remove the relevant accessory/persist files in your HomeBridge directory manually, or you can remove them using the HomeBridge UI:

<img width="561" alt="Screen Shot 2022-10-09 at 8 49 07 PM" src="https://user-images.githubusercontent.com/1072488/194744568-f9794e25-2501-4462-bbf3-18d1114b0c84.png">

**Comment by slydlake** [comment]
Thanks! That is the solution 😊
